services:
  php:
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    container_name: newsfeed-app
    volumes:
      - ./:/app
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  webserver:
    image: "nginx:alpine"
    container_name: newsfeed-webserver
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"